### ISSUE TITLE
How to handle graphite multi-valued metrics

### ISSUE THREAD

**Issue by tlk2126** [Graphite-Tattle/Graphite-Tattle#19]
Graphite allows you to ask for something like `system.*.cpu_load' and get back an array of data for everything that matches that pattern --- you get back a json array for `system.host_a.cpu_load' and `system.host_b.cpu_load', etc.

For our use, we'd like to be able to get alerts for any of those wildcarded metrics going over the limit, e.g. "Any system load over 3" or whatnot. Right now, Tattle accepts that as a metric, but only does notification for the first metric that happens to be reported (Check::getResultValue explicitly looks at $data[0]). 

Setting aside the future issue of things like "I want notified for all system's cpu load over 3, except big_host, where I don't care until it reaches 10, or test_host, where I don't care at all", I'd like to figure out the sanest way of handling this. Has anyone else thought of this, or wanted this? I've got a few ideas on how to handle the simple case, but I wanted to check with other folks before going too far down that road.

**Comment by mreeves1** [comment]
One thing I learned today is there is a boolean OR you can apply. So in @tlk2126 's case you could use
system.{host_a,host_b}.cpu_load so you could leave out test_host...

**Comment by g76r** [comment]
@tlk2126 I think this is definitely an issue to be solved using graphite target syntax, being them {} instead of * as proposed by @mreeves1 or being them functions like maxSeries() and exclude() (see http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.exclude).
Therefore I close the issue.
