### ISSUE TITLE
Add better null handling to checks

### ISSUE THREAD

**Issue by ssandler** [Graphite-Tattle/Graphite-Tattle#27]
Currently if you have a metric that is reported only semi-frequently (i.e. a job that runs every 1 or 2 minutes) you'll get a lot of nulls back from graphite which throw off the averages and medians. You can wrap the target in a keepLastValue() function but it can still end up with nulls at the beginning of the results. We should probably ignore nulls, but we need to handle the case of all results being nulls. 

It'd also be nice to have an option to explicitly alert on all the values being null (i.e. if my job that sends data to graphite is broken, alert on the fact that graphite is not getting any data).

**Comment by g76r** [comment]
@ssandler I don't think that Tattle should ignore nulls in every case, maybe it could be a checkbox or whatever option, if you wan't to do such a pull request, but anyway graphite's transformNull() function can do the job as well (see http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.transformNull)
