### ISSUE TITLE
Remove the moving-average requirement.

### ISSUE THREAD

**Issue by otac0n** [Graphite-Tattle/Graphite-Tattle#31]
We are using graphite to track an error bucket of sorts.

We need to get alerts anytime this bucket has more than zero items in in.

There are several issues with Graphite-Tattle that prevent us from doing this effectively:
1.  We are unable to turn off moving averages (aside from using a single sample).
2.  We are unable to tell Graphite-Tattle to look at a shorter window than 1 day.  When looking at a 1 day window, the values are averaged.
3.  We don't want separate error or warning thresholds here (but we can use 0.5 for warnings as a workaround).

Thoughts?

**Comment by g76r** [comment]
movingAverage() can now be disabled by setting "sample size" threshold check field to 1

"now" means merged in master since a few minutes
