### ISSUE TITLE
Best practice to implement processor.php cron job?

### ISSUE THREAD

**Issue by mreeves1** [Graphite-Tattle/Graphite-Tattle#53]
I originally tried running processor.php in root's cron job like so:
*/5 * * * * php /var/www/html/Graphite-Tattle/processor.php
but I got path errors. 

So I made a change in /inc/init.php because getcwd will not always set the root correctly unless you are currently in the Graphite-Tattle directory. 
I replaced
define('TATTLE_ROOT', str_replace(array('ajax'),'',getcwd()));
with: 
define('TATTLE_ROOT', str_replace(array('ajax'),'',dirname($_SERVER['SCRIPT_FILENAME'])));

one caveat is I am using the f80 fork of Graphite-Tattle so the next bit may not be relevant. 

I tried running the cron so it appeared to be done by the apache user and it seems to succeed (writes to log, sets alerts, etc.). 
*/5 * * * * su -s /bin/sh -c "php /var/www/html/Graphite-Tattle/processor.php -debug >> /var/www/html/Graphite-Tattle/logs/debug.log 2>> /var/www/html/Graphite-Tattle/logs/errors.log" apache

But for some reason I would not receive email notifications. I checked logs, etc. and everything seems fine. 

However, I had noticed if I hit processor.php from the web client it worked. So I decided to try this:
*/5 * * * * curl 127.0.0.1/Graphite-Tattle/processor.php?debug=true >> /var/www/html/Graphite-Tattle/logs/debug.log
which works. 

I just wanted to see if anyone had any better advice on how to run processor.php. I was thinking I may add in my curl command crontab to the README as a pull request if you like.

**Comment by g76r** [comment]
As for now I won't personally spend time on making processor.php callable on the command line rather than through http, but if someone wants to do so, I would find it nice.
Anyway I reworded README regarding processor.php triggering.
